theme = "catppuccin_mocha"

[editor]
true-color = true
line-number = "relative"
bufferline = "multiple"
auto-completion = true
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
